#!/bin/bash
myCon="${HOME}/Downloads/myCon"
vimrc="${HOME}/.vimrc"
vundlePath="${HOME}/.vim/bundle/Vundle.vim"
ftdetectRelPath="/.vim/ftdetect"
ftdetect="${HOME}${ftdetectRelPath}"

function getVim {
	if [ -f "${vimrc}" ]; then
		echo "A .vimrc file already exists"
	else
		ln -s "${myCon}/configs/.vimrc" "${vimrc}"
	fi

	if [ -d "${vundlePath}" ]; then
		echo "We already have vundle, moving on"
	else
		git clone https://github.com/VundleVim/Vundle.vim.git "${vundlePath}" && echo "vundle installed"
	fi

	if [ -d "${ftdetect}" ]; then
		echo "A ftdetect dir already exists"
	else
		ln -s "${myCon}/configs/${ftdetectRelPath}" "${ftdetect}"
	fi
	vim +PluginInstall +qall
	cd "${HOME}/.vim/bundle/vimproc.vim" && make || echo "Issue with building vimproc"
}
