#!/bin/bash
myCon="${HOME}/Downloads/myCon"
vimrc="${HOME}/.vimrc"

function getVim {
	git clone https://github.com/VundleVim/Vundle.vim.git "${HOME}/.vim/bundle/Vundle.vim"
	if [ -f "${vimrc}" ]; then
		echo "A .vimrc file already exists"
	else
		ln -s "${myCon}/configs/.vimrc" "${zshrc}"
	fi
	vim +PluginInstall +qall
}
