#!/bin/bash
myCon="${HOME}/Downloads/myCon"
zshrc="${HOME}/.zshrc"

function getZsh {
	# sh -c "$(wget https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh -O -)"
	if [ -f "${zshrc}" ]; then
		echo "A .zshrc file already exists"
	else
		ln -s "${myCon}/configs/.zshrc" ${zshrc}
	fi
}
